# Reseni IOS-proj2, 11.04.2024
# Autor: Radim Dvorak, xdvorar00

CC=gcc
CFLAGS= -std=gnu99 -g -Wall -Wextra -Werror -pedantic -pthread -lrt
PROGS= proj2

all: $(PROGS)

pack:
	zip proj2.zip proj2.c Makefile

clean:
	rm -f $(PROGS) *.o